version: '3.1'
services:
  mibus_api:
    build: .
    image: mibus_api
    container_name: mibus_api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      PGDATABASE: ${PGDATABASE}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGUSER: ${PGUSER}
      BUSES_API: ${BUSES_API}
      BUS_NORMAL_STATE: ${BUS_NORMAL_STATE}
      BUSES_REFRESH: ${BUSES_REFRESH}
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 9000:5432
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
    depends_on:
      - db

volumes:
  db:
    driver: local